default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['DB_HOST'] || '127.0.0.1' %>
  port: <%= ENV['DB_PORT'] || '5432' %>
  username: <%= ENV['DB_USERNAME'] || 'postgres' %>
  password: <%= ENV['DB_PASSWORD'] || 'secret' %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV['DB_DATABASE'] || 'r2_dev' %>

test:
  <<: *default
  database: <%= ENV['DB_DATABASE'] || 'r2_test' %>

production:
  <<: *default
  database: <%= ENV['DB_DATABASE'] || 'r2_production' %>
